#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x4D8592DF4CE1ED31 (elic@astllc.org)
#
Name     : passlib
Version  : 1.6.5
Release  : 21
URL      : https://pypi.python.org/packages/source/p/passlib/passlib-1.6.5.tar.gz
Source0  : https://pypi.python.org/packages/source/p/passlib/passlib-1.6.5.tar.gz
Source99 : https://pypi.python.org/packages/source/p/passlib/passlib-1.6.5.tar.gz.asc
Summary  : comprehensive password hashing framework supporting over 30 schemes
Group    : Development/Tools
License  : BSD-3-Clause
Requires: passlib-python
BuildRequires : nose-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
==========================
The Passlib Python Library
==========================

%package python
Summary: python components for the passlib package.
Group: Default

%description python
python components for the passlib package.


%prep
%setup -q -n passlib-1.6.5

%build
export LANG=C
export SOURCE_DATE_EPOCH=1484561036
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
py.test-2.7 || :
%install
export SOURCE_DATE_EPOCH=1484561036
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
